name: Create Release

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Release Tag
        id: generate_tag
        run: |
          # Получаем текущую дату
          TODAY=$(TZ=Europe/Moscow date +'%Y.%m.%d')
          echo "Base tag: $TODAY"
          
          # Получаем все существующие теги из текущего репозитория
          git fetch --tags
          git tag -l > local_tags.txt
          
          # Считаем количество релизов для этой даты
          EXISTING_TAGS=$(grep -c "^$TODAY" local_tags.txt || true)
          echo "Existing tags for today: $EXISTING_TAGS"
          
          # Считаем общее количество релизов (только с паттерном даты)
          TOTAL_RELEASES=$(grep -c -E '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}' local_tags.txt || true)
          echo "Total releases: $TOTAL_RELEASES"
          
          if [ $EXISTING_TAGS -eq 0 ]; then
            RELEASE_TAG="$TODAY"
          else
            RELEASE_TAG="${TODAY}-patch${EXISTING_TAGS}"
          fi
          
          echo "Generated tag: $RELEASE_TAG"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "VERSION_CODE=$((TOTAL_RELEASES + 1))" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: 'jdk'
          cache: 'gradle'

      - name: Build JAR with Version
        run: |
          bash ./gradlew jar \
            -PversionName=${{ steps.generate_tag.outputs.RELEASE_TAG }}

      - name: MV JAR file to root
        run: |
          mv ./build/libs/Update-repos-${{ steps.generate_tag.outputs.RELEASE_TAG }}.jar ./Update-repos-${{ steps.generate_tag.outputs.RELEASE_TAG }}.jar

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ steps.generate_tag.outputs.RELEASE_TAG }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./Update-repos-${{ steps.generate_tag.outputs.RELEASE_TAG }}.jar
          tag_name: ${{ steps.generate_tag.outputs.RELEASE_TAG }}
          name: ${{ steps.generate_tag.outputs.RELEASE_TAG }}